const house =[
    {
        id:'1',
        meme:'đồng hồ chất lượng cao!!!',
        ratting:'205 Ratting',
        poin:'7.5',
        title:'Rolex Cellinit',
        watch:'Fashion',
        title:'Lady-Datejust',
        location:'Mẫu mới 2021,Oyster, 28 mm ',
        price:'450.000$',
        tim:'169+',
        image: require('../assets/products/rolex3.png'),
        details:'Đồng hồ Oyster Perpetual Lady-Datejust bằng vàng vàng 18 ct đi kèm mặt số đính kim cương và dây đeo bộ President nạm kim cương.',
        like: true,
        interiors:[
            require('../assets/products/rolex3a.jpg'),
            require('../assets/products/rolex3b.jpg'),
            require('../assets/products/rolex3c.jpg'),
            require('../assets/products/rolex3d.jpg'),
            require('../assets/products/rolex3e.jpg'),
        ],
    },
    {
        id:'2',
        meme:'đồng hồ chất lượng cao!!!',
        ratting:'399 Ratting',
        poin:'8.9',
        title:'Rolex Cellinit',
        watch:'Speed',
        title:'Cosmograph Daytona',
        location:'Mẫu mới 2021,Oyster, 40 mm ',
        tim:'408+',
        price:'250.000$',
        image: require('../assets/products/rolexs1.jpg'),
        details:'Đồng hồ Oyster Perpetual Cosmograph Daytona bằng vàng trắng 18ct với mặt số đá thiên thạch đen và dây đeo Oysterflex, tích hợp vành đồng hồ Cerachrom đen và thang đo tốc độ tinh xảo.',
        like: true,
        interiors:[
            require('../assets/products/rolexhd1a.jpg'),
            require('../assets/products/rolexhd1b.jpg'),
            require('../assets/products/rolexhd1c.jpg'),
            require('../assets/products/rolexhd1d.jpg'),
            require('../assets/products/rolexhd1e.jpg'),
        ],
    },
   
     
    {
        id:'3',
        meme:'đồng hồ chất lượng cao!!!',
        ratting:'145 Ratting',
        poin:'9.6',
        title:'Rolex Cellinit',
        watch:'Classical',
        location:'39 mm, vàng Everose 18 ct ',
        price:'150.000$',
        image: require('../assets/products/rolex1.jpg'),
        details:'Đồng hồ Cellini Moonphase bằng vàng Everose 18 ct với Dây đeo da.Mẫu đồng hồ này có màn hình độc quyền của các giai đoạn của mặt trăng. ',
        like: true,
        tim:'132+',
        interiors:[
            require('../assets/products/rolex1a.jpg'),
            require('../assets/products/rolex1b.jpg'),
            require('../assets/products/rolex1c.jpg'),
            require('../assets/products/rolex1d.jpg'),
        ],
    },
    
];
export default house;